-- Initial schema migration for Flyway.
-- Generated from PostgreSQL schema dump and cleaned for application migration use.
-- Notes:
--   - Removed pg_dump metadata, OWNER statements, COPY data, and flyway_schema_history.
--   - Keep seed data in a separate migration file, e.g. V2__seed_admin_user.sql.

CREATE SCHEMA IF NOT EXISTS public;

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';
SET default_table_access_method = heap;

CREATE TABLE public.configurations (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    config_key character varying(100) NOT NULL,
    config_value text NOT NULL,
    description character varying(255) NOT NULL
);

ALTER TABLE public.configurations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.configurations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.library_card_requests (
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    delivery_address character varying(255) NOT NULL,
    note character varying(255),
    status character varying(255) NOT NULL,
    CONSTRAINT library_card_requests_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);

CREATE TABLE public.reservations (
    cancel_date timestamp(6) without time zone,
    confirm_date timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    reservation_date timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    book_item_id uuid NOT NULL,
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT reservations_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'CANCELLED'::character varying, 'EXPIRED'::character varying])::text[])))
);

CREATE TABLE public.tbl_aisle (
    floor_id uuid,
    id uuid NOT NULL,
    name character varying(255),
    status character varying(255),
    CONSTRAINT tbl_aisle_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);

CREATE TABLE public.tbl_audit_log (
    created_at timestamp(6) with time zone NOT NULL,
    id uuid NOT NULL,
    user_id uuid,
    status character varying(20) NOT NULL,
    ip_address character varying(45),
    action character varying(100) NOT NULL,
    entity_id character varying(100),
    entity_name character varying(100) NOT NULL,
    username character varying(100),
    user_agent character varying(500),
    message text,
    metadata text,
    CONSTRAINT tbl_audit_log_action_check CHECK (((action)::text = ANY ((ARRAY['LOGIN'::character varying, 'LOGOUT'::character varying, 'SIGN_UP'::character varying, 'REFRESH_TOKEN'::character varying, 'CHANGE_PASSWORD'::character varying, 'FORGOT_PASSWORD'::character varying, 'RESET_PASSWORD'::character varying, 'CREATE'::character varying, 'UPDATE'::character varying, 'DELETE'::character varying, 'RESTORE'::character varying, 'BORROW_CREATED'::character varying, 'RETURN_SUCCESS'::character varying, 'DAMAGE_DETECTED'::character varying, 'ITEM_LOST'::character varying, 'OVERDUE_DETECTED'::character varying, 'PAYMENT_TRIGGERED'::character varying])::text[]))),
    CONSTRAINT tbl_audit_log_entity_name_check CHECK (((entity_name)::text = ANY ((ARRAY['USER'::character varying, 'AUTH'::character varying, 'ORDER'::character varying, 'SUBSCRIPTION'::character varying, 'CATEGORY'::character varying, 'BOOK'::character varying, 'BOOK_ITEM'::character varying, 'RENTAL'::character varying, 'FINE'::character varying, 'WAREHOUSE'::character varying])::text[]))),
    CONSTRAINT tbl_audit_log_status_check CHECK (((status)::text = ANY ((ARRAY['SUCCESS'::character varying, 'FAILED'::character varying])::text[])))
);

CREATE TABLE public.tbl_book (
    count integer NOT NULL,
    price integer NOT NULL,
    published_year integer,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    category_id uuid,
    id uuid NOT NULL,
    author character varying(255) NOT NULL,
    description text,
    isbn character varying(255) NOT NULL,
    publishers character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    thumbnail_url character varying(255),
    title character varying(255) NOT NULL,
    CONSTRAINT tbl_book_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'DELETED'::character varying])::text[])))
);

CREATE TABLE public.tbl_bookitem (
    import_date date,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    book_id uuid NOT NULL,
    id uuid NOT NULL,
    shelf_position_id uuid,
    status character varying(20) NOT NULL,
    barcode character varying(255) NOT NULL,
    CONSTRAINT tbl_bookitem_status_check CHECK (((status)::text = ANY ((ARRAY['AVAILABLE'::character varying, 'BORROWED'::character varying, 'LOST'::character varying, 'DAMAGED'::character varying, 'MAINTENANCE'::character varying, 'DISCARDED'::character varying, 'PENDING'::character varying, 'INACTIVE'::character varying, 'DELETED'::character varying])::text[])))
);

CREATE TABLE public.tbl_category (
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    id uuid NOT NULL,
    status character varying(20) NOT NULL,
    title character varying(100) NOT NULL,
    CONSTRAINT tbl_category_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'DELETED'::character varying])::text[])))
);

CREATE TABLE public.tbl_fine (
    amount integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    id uuid NOT NULL,
    rental_id uuid NOT NULL,
    reason character varying(500) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT tbl_fine_status_check CHECK (((status)::text = ANY ((ARRAY['UNPAID'::character varying, 'PAID'::character varying, 'CANCELED'::character varying])::text[])))
);

CREATE TABLE public.tbl_floor (
    id uuid NOT NULL,
    name character varying(255),
    status character varying(255),
    CONSTRAINT tbl_floor_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);

CREATE TABLE public.tbl_library_card (
    expiry_date date NOT NULL,
    issue_date date NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT tbl_library_card_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'EXPIRED'::character varying, 'INACTIVE'::character varying, 'BLOCKED'::character varying, 'LOST'::character varying])::text[])))
);

CREATE TABLE public.tbl_payment (
    amount double precision NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    fine_id uuid,
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    user_subscription_id uuid,
    payment_status character varying(255) NOT NULL,
    payment_type character varying(255) NOT NULL,
    CONSTRAINT tbl_payment_payment_status_check CHECK (((payment_status)::text = ANY ((ARRAY['PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying])::text[]))),
    CONSTRAINT tbl_payment_payment_type_check CHECK (((payment_type)::text = ANY ((ARRAY['FINE'::character varying, 'SUBSCRIPTION'::character varying])::text[])))
);

CREATE TABLE public.tbl_position (
    book_count integer NOT NULL,
    col_index integer NOT NULL,
    row_index integer NOT NULL,
    id uuid NOT NULL,
    shelf_id uuid
);

CREATE TABLE public.tbl_rental (
    due_date date NOT NULL,
    rent_date date NOT NULL,
    return_date date,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    book_item_id uuid NOT NULL,
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT tbl_rental_status_check CHECK (((status)::text = ANY ((ARRAY['BORROWING'::character varying, 'RETURNED'::character varying, 'OVERDUE'::character varying, 'LOST'::character varying])::text[])))
);

CREATE TABLE public.tbl_shelf (
    max_col integer NOT NULL,
    max_row integer NOT NULL,
    aisle_id uuid,
    id uuid NOT NULL,
    name character varying(255)
);

CREATE TABLE public.tbl_subscription (
    compensation_rate integer NOT NULL,
    duration_days integer NOT NULL,
    max_books integer NOT NULL,
    max_renewals integer NOT NULL,
    overdue_fee_per_day integer NOT NULL,
    price integer NOT NULL,
    id uuid NOT NULL,
    status character varying(20) NOT NULL,
    key character varying(50) NOT NULL,
    name character varying(255) NOT NULL,
    CONSTRAINT tbl_subscription_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'DELETED'::character varying])::text[])))
);

CREATE TABLE public.tbl_user (
    birthday date,
    gender boolean NOT NULL,
    password_changed boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    last_login_at timestamp(6) with time zone,
    refresh_token_expired_at timestamp(6) with time zone,
    reset_password_token_expired_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone NOT NULL,
    id uuid NOT NULL,
    identity_number character varying(20),
    phone character varying(20),
    role character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    username character varying(100) NOT NULL,
    avatar_url character varying(500),
    identity_back_url character varying(500),
    identity_front_url character varying(500),
    address text,
    email character varying(255),
    full_name character varying(255),
    password_hash character varying(255) NOT NULL,
    refresh_token_hash character varying(255),
    reset_password_token_hash character varying(255),
    CONSTRAINT tbl_user_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'MANAGER'::character varying, 'USER'::character varying])::text[]))),
    CONSTRAINT tbl_user_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'LOCKED'::character varying, 'DELETED'::character varying])::text[])))
);

CREATE TABLE public.tbl_user_subscription (
    end_date date NOT NULL,
    max_books integer NOT NULL,
    price integer NOT NULL,
    start_date date NOT NULL,
    id uuid NOT NULL,
    subscription_id uuid NOT NULL,
    user_id uuid NOT NULL,
    status character varying(20) NOT NULL,
    CONSTRAINT tbl_user_subscription_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'EXPIRED'::character varying, 'CANCELED'::character varying])::text[])))
);

SELECT pg_catalog.setval('public.configurations_id_seq', 1, false);

ALTER TABLE ONLY public.configurations
    ADD CONSTRAINT configurations_config_key_key UNIQUE (config_key);

ALTER TABLE ONLY public.configurations
    ADD CONSTRAINT configurations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.library_card_requests
    ADD CONSTRAINT library_card_requests_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT reservations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tbl_aisle
    ADD CONSTRAINT tbl_aisle_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tbl_audit_log
    ADD CONSTRAINT tbl_audit_log_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tbl_book
    ADD CONSTRAINT tbl_book_isbn_key UNIQUE (isbn);

ALTER TABLE ONLY public.tbl_book
    ADD CONSTRAINT tbl_book_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tbl_bookitem
    ADD CONSTRAINT tbl_bookitem_barcode_key UNIQUE (barcode);

ALTER TABLE ONLY public.tbl_bookitem
    ADD CONSTRAINT tbl_bookitem_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tbl_category
    ADD CONSTRAINT tbl_category_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tbl_category
    ADD CONSTRAINT tbl_category_title_key UNIQUE (title);

ALTER TABLE ONLY public.tbl_fine
    ADD CONSTRAINT tbl_fine_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tbl_fine
    ADD CONSTRAINT tbl_fine_rental_id_key UNIQUE (rental_id);

ALTER TABLE ONLY public.tbl_floor
    ADD CONSTRAINT tbl_floor_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tbl_library_card
    ADD CONSTRAINT tbl_library_card_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tbl_payment
    ADD CONSTRAINT tbl_payment_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tbl_position
    ADD CONSTRAINT tbl_position_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tbl_rental
    ADD CONSTRAINT tbl_rental_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tbl_shelf
    ADD CONSTRAINT tbl_shelf_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tbl_subscription
    ADD CONSTRAINT tbl_subscription_key_key UNIQUE (key);

ALTER TABLE ONLY public.tbl_subscription
    ADD CONSTRAINT tbl_subscription_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tbl_user
    ADD CONSTRAINT tbl_user_email_key UNIQUE (email);

ALTER TABLE ONLY public.tbl_user
    ADD CONSTRAINT tbl_user_identity_number_key UNIQUE (identity_number);

ALTER TABLE ONLY public.tbl_user
    ADD CONSTRAINT tbl_user_phone_key UNIQUE (phone);

ALTER TABLE ONLY public.tbl_user
    ADD CONSTRAINT tbl_user_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tbl_user_subscription
    ADD CONSTRAINT tbl_user_subscription_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tbl_user
    ADD CONSTRAINT tbl_user_username_key UNIQUE (username);

CREATE INDEX idx_audit_log_action ON public.tbl_audit_log USING btree (action);

CREATE INDEX idx_audit_log_created_at ON public.tbl_audit_log USING btree (created_at);

CREATE INDEX idx_audit_log_user_id ON public.tbl_audit_log USING btree (user_id);

CREATE INDEX idx_user_refresh_token_hash ON public.tbl_user USING btree (refresh_token_hash);

CREATE INDEX idx_user_reset_password_token_hash ON public.tbl_user USING btree (reset_password_token_hash);

CREATE INDEX idx_user_role ON public.tbl_user USING btree (role);

CREATE INDEX idx_user_status ON public.tbl_user USING btree (status);

CREATE INDEX idx_user_subscription_end_date ON public.tbl_user_subscription USING btree (end_date);

CREATE INDEX idx_user_subscription_start_date ON public.tbl_user_subscription USING btree (start_date);

CREATE INDEX idx_user_subscription_status ON public.tbl_user_subscription USING btree (status);

CREATE INDEX idx_user_subscription_subscription_id ON public.tbl_user_subscription USING btree (subscription_id);

CREATE INDEX idx_user_subscription_user_id ON public.tbl_user_subscription USING btree (user_id);

ALTER TABLE ONLY public.tbl_book
    ADD CONSTRAINT fk1urfopwhog7px2krf84lnrih2 FOREIGN KEY (category_id) REFERENCES public.tbl_category(id);

ALTER TABLE ONLY public.tbl_user_subscription
    ADD CONSTRAINT fk4rvixs1fm01ismos6biqi9kot FOREIGN KEY (user_id) REFERENCES public.tbl_user(id);

ALTER TABLE ONLY public.library_card_requests
    ADD CONSTRAINT fk5rndr2ae4a2in0xcb0dpryoyc FOREIGN KEY (user_id) REFERENCES public.tbl_user(id);

ALTER TABLE ONLY public.tbl_fine
    ADD CONSTRAINT fk60hylowjj15an0y9qafokwv3k FOREIGN KEY (rental_id) REFERENCES public.tbl_rental(id);

ALTER TABLE ONLY public.tbl_aisle
    ADD CONSTRAINT fkc1eh2yha3k8v62th7khv7u0b4 FOREIGN KEY (floor_id) REFERENCES public.tbl_floor(id);

ALTER TABLE ONLY public.tbl_user_subscription
    ADD CONSTRAINT fkcd4o6k5wcmsqkjh9u7dgj6i1o FOREIGN KEY (subscription_id) REFERENCES public.tbl_subscription(id);

ALTER TABLE ONLY public.tbl_position
    ADD CONSTRAINT fkhy9qv9dxs9ua41oppku0s1kxp FOREIGN KEY (shelf_id) REFERENCES public.tbl_shelf(id);

ALTER TABLE ONLY public.tbl_bookitem
    ADD CONSTRAINT fklwy7tmqeqy26r4731667a69fa FOREIGN KEY (shelf_position_id) REFERENCES public.tbl_position(id);

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT fkm2x747o9c38062bj533o2y661 FOREIGN KEY (user_id) REFERENCES public.tbl_user(id);

ALTER TABLE ONLY public.tbl_bookitem
    ADD CONSTRAINT fkqaif73jmxh3wk0xalva0of0r9 FOREIGN KEY (book_id) REFERENCES public.tbl_book(id);

ALTER TABLE ONLY public.tbl_shelf
    ADD CONSTRAINT fkrtrn8y20lqaqwkclfew26v2g4 FOREIGN KEY (aisle_id) REFERENCES public.tbl_aisle(id);

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT fktaj43fkk19q5yr21q86csik9q FOREIGN KEY (book_item_id) REFERENCES public.tbl_bookitem(id);
