ALTER TABLE public.tbl_audit_log DROP CONSTRAINT IF EXISTS tbl_audit_log_action_check;
ALTER TABLE public.tbl_audit_log DROP CONSTRAINT IF EXISTS tbl_audit_log_entity_name_check;

ALTER TABLE public.tbl_audit_log ADD CONSTRAINT tbl_audit_log_action_check
    CHECK (((action)::text = ANY ((ARRAY[
        'LOGIN','LOGOUT','SIGN_UP','REFRESH_TOKEN','CHANGE_PASSWORD','FORGOT_PASSWORD','RESET_PASSWORD',
        'CREATE','UPDATE','DELETE','RESTORE',
        'BORROW_CREATED','RETURN_SUCCESS','RENEW_SUCCESS','DAMAGE_DETECTED','ITEM_LOST','OVERDUE_DETECTED','PAYMENT_TRIGGERED',
        'FINE_PAID','PAYMENT_CREATED','PAYMENT_CONFIRMED',
        'SUBSCRIPTION_CREATED','SUBSCRIPTION_UPDATED','SUBSCRIPTION_DELETED',
        'USER_SUBSCRIPTION_CREATED','USER_SUBSCRIPTION_UPDATED','USER_SUBSCRIPTION_CANCELED',
        'LIBRARY_CARD_CREATED','LIBRARY_CARD_UPDATED','LIBRARY_CARD_LOCKED','LIBRARY_CARD_REPLACED','LIBRARY_CARD_LOST_REPORTED',
        'LIBRARY_CARD_REQUEST_CREATED','LIBRARY_CARD_REQUEST_APPROVED','LIBRARY_CARD_REQUEST_REJECTED','LIBRARY_CARD_REQUEST_CANCELED',
        'NOTIFICATION_CREATED','NOTIFICATION_BULK_CREATED',
        'CONFIGURATION_UPDATED'
    ])::text[])));

ALTER TABLE public.tbl_audit_log ADD CONSTRAINT tbl_audit_log_entity_name_check
    CHECK (((entity_name)::text = ANY ((ARRAY[
        'USER','AUTH','ORDER','SUBSCRIPTION','USER_SUBSCRIPTION','CATEGORY',
        'BOOK','BOOK_ITEM','RENTAL','FINE','PAYMENT',
        'LIBRARY_CARD','LIBRARY_CARD_REQUEST',
        'WAREHOUSE','NOTIFICATION','CONFIGURATION','REPORT'
    ])::text[])));
